apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy:1.0.0-16
  labels:
    app: swiggy:1.0.0-16
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy:1.0.0-16
  template:
    metadata:
      labels:
        app: swiggy:1.0.0-16
    spec:
      containers:
      - name: swiggy:1.0.0-16
        image: raemondarellano/swiggy:1.0.0-16
        ports:
        - containerPort: 3000
