apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-swiggy:1.0.0-22
  labels:
    app: application-swiggy:1.0.0-22
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-swiggy:1.0.0-22
  template:
    metadata:
      labels:
        app: application-swiggy:1.0.0-22
    spec:
      containers:
      - name: application-swiggy:1.0.0-22
        image: raemondarellano/swiggy:1.0.0-22
        ports:
        - containerPort: 3000
