apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-swiggy-deployment
  labels:
    app: application-swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-swiggy
  template:
    metadata:
      labels:
        app: application-swiggy
    spec:
      containers:
      - name: application-swiggy
        image: raemondarellano/swiggy:1.0.0-16
        ports:
        - containerPort: 3000
