apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-deployment-app
  labels:
    app: swiggy-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-application
  template:
    metadata:
      labels:
        app: swiggy-application
    spec:
      containers:
      - name: swiggy-application
        image: raemondarellano/swiggy:1.0.0-13
        ports:
        - containerPort: 3000
