apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy:1.0.0-13
  labels:
    app: swiggy:1.0.0-13
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy:1.0.0-13
  template:
    metadata:
      labels:
        app: swiggy:1.0.0-13
    spec:
      containers:
      - name: swiggy:1.0.0-13
        image: raemondarellano/swiggy:1.0.0-13
        ports:
        - containerPort: 3000
