apiVersion: v1
kind: Service
metadata:
  name: swiggy-app-service
  labels:
    app:  swiggy-application
spec:
  type: NodePort
  ports:  
  - port: 80
    targetPort: 3000
  # selector:
  #   app: swiggy-app




